### ISSUE TITLE
zone.js/dist/zone-node.js creates Error listen EADDRINUSE: address already in use :::8080 - on firebase

### ISSUE THREAD

**Issue by mappedinn** [Ismaestro/angular8-example-app#45]
**Describe the bug**

zone.js/dist/zone-node.js creates Error listen EADDRINUSE: address already in use :::8080 - on firebase

```
Function execution started
Billing account not configured. External network is not accessible and quotas are severely limited. Configure billing account to remove these restrictions
Node Express server listening on port 8080
/srv/functions/node_modules/zone.js/dist/zone-node.js:199

throw error;
ssr
^

 Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1270:14)
    at listenInCluster (net.js:1318:12)
    at Server.listen (net.js:1405:7)
    at Object.<anonymous> (/srv/node_modules/@google-cloud/functions-framework/build/src/index.js:56:8)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Emitted 'error' event at:
at emitErrorNT (net.js:1297:8)
at ZoneDelegate.invokeTask (/srv/functions/node_modules/zone.js/dist/zone-node.js:423:31)
at Zone.runTask (/srv/functions/node_modules/zone.js/dist/zone-node.js:195:47)
at ZoneTask.invokeTask (/srv/functions/node_modules/zone.js/dist/zone-node.js:498:34)
at ZoneTask.invoke (/srv/functions/node_modules/zone.js/dist/zone-node.js:487:48)
at data.args.(anonymous function) (/srv/functions/node_modules/zone.js/dist/zone-node.js:1421:25)
at process._tickCallback (internal/process/next_tick.js:63:19)
at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
at startup (internal/bootstrap/node.js:283:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Error: cannot communicate with function. Function invocation was interrupted.
```

**To Reproduce**

```sh
npm run build:ssr
npm run deploy
```

**Expected behavior**

Avoid the EADDRINUSE error

**Screenshots**
NONE

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser: firefox
 - Version: 67

**Smartphone (please complete the following information):**

NONE

**Additional context**

After building the application with `npm run build:ssr`, the application is working locally (through the command `firebase serve`) with **the EADDRINUSE error** but without stop the server.

```
(base) amine@amine-X580VD:~/Documents/docker-projects/angular7-example-app/functions$ firebase serve

=== Serving from '/home/amine/Documents/docker-projects/angular7-example-app'...

⚠  Your requested "node" version "10" doesn't match your global version "11"
✔  functions: Emulator started at http://localhost:5001
i  functions: Watching "/home/amine/Documents/docker-projects/angular7-example-app/functions" for Cloud Functions...
i  hosting: Serving hosting files from: functions/dist
✔  hosting: Local server: http://localhost:5000
>  Node Express server listening on port 4000
i  functions: HTTP trigger initialized at http://localhost:5001/mohamed-amine-jallouli/us-central1/ssr
[hosting] Rewriting / to http://localhost:5001/mohamed-amine-jallouli/us-central1/ssr for local Function ssr
i  functions: Beginning execution of "ssr"
>  /home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:199
>                          throw error;
>                          ^
>  
>  Error: listen EADDRINUSE: address already in use :::4000
>      at Server.setupListenHandle [as _listen2] (net.js:1259:14)
>      at listenInCluster (net.js:1307:12)
>      at Server.listen (net.js:1395:7)
>      at Function.listen (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/express/lib/application.js:618:24)
>      at Object.<anonymous> (/home/amine/Documents/docker-projects/angular7-example-app/functions/index.js:51:5)
>      at Module._compile (internal/modules/cjs/loader.js:816:30)
>      at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
>      at Module.load (internal/modules/cjs/loader.js:685:32)
>      at Function.Module._load (internal/modules/cjs/loader.js:620:12)
>      at Module.require (internal/modules/cjs/loader.js:723:19)
>      at require (internal/modules/cjs/helpers.js:14:16)
>      at /usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:459:29
>      at Generator.next (<anonymous>)
>      at /usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
>      at new Promise (<anonymous>)
>      at __awaiter (/usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:3:12)
>      at main (/usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:421:12)
>      at Object.<anonymous> (/usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:511:5)
>      at Module._compile (internal/modules/cjs/loader.js:816:30)
>      at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
>      at Module.load (internal/modules/cjs/loader.js:685:32)
>      at Function.Module._load (internal/modules/cjs/loader.js:620:12)
>      at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
>      at internal/main/run_main_module.js:21:11
>  Emitted 'error' event at:
>      at emitErrorNT (net.js:1286:8)
>      at ZoneDelegate.invokeTask (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:423:31)
>      at Zone.runTask (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:195:47)
>      at ZoneTask.invokeTask (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:498:34)
>      at ZoneTask.invoke (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:487:48)
>      at data.args.(anonymous function) (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:1421:25)
>      at processTicksAndRejections (internal/process/task_queues.js:81:17)
>      at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
>      at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
>      at internal/main/run_main_module.js:21:11
>  Angular library has started with this options:  { config: { say: 'hello' } }
>  (node:4826) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
>  { Error [FirebaseError]: The query requires an index. You can create it here: https://console.firebase.google.com/project/mohamed-amine-jallouli/database/firestore/indexes?create_composite=ClVwcm9qZWN0cy9tb2hhbWVkLWFtaW5lLWphbGxvdWxpL2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9oZXJvZXMvaW5kZXhlcy9fEAEaCwoHZGVmYXVsdBACGgkKBWxpa2VzEAIaDAoIX19uYW1lX18QAg
>      at new FirestoreError (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js:353:28)
>      at JsonProtoSerializer.fromRpcStatus (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js:5579:16)
>      at JsonProtoSerializer.fromWatchChange (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js:6076:44)
>      at PersistentListenStream.onMessage (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js:14286:43)
>      at /home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js:14215:30
>      at /home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js:14255:28
>      at /home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js:7343:20
>      at ZoneDelegate.invoke (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:391:26)
>      at Zone.run (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:150:43)
>      at /home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:889:34
>      at ZoneDelegate.invokeTask (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:423:31)
>      at Zone.runTask (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:195:47)
>      at drainMicroTaskQueue (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:601:35)
>      at ZoneTask.invokeTask (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:502:21)
>      at ClientDuplexStream.ZoneTask.invoke (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:487:48)
>      at ClientDuplexStream.emit (events.js:193:13)
>      at ClientDuplexStream.EventEmitter.emit (domain.js:481:20)
>      at addChunk (_stream_readable.js:295:12)
>      at readableAddChunk (_stream_readable.js:276:11)
>      at ClientDuplexStream.Readable.push (_stream_readable.js:231:10)
>      at Object.onReceiveMessage (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/grpc/src/client_interceptors.js:1292:19)
>      at InterceptingListener.recvMessageWithContext (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/grpc/src/client_interceptors.js:607:19)
>      at /home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/grpc/src/client_interceptors.js:706:14
>    code: 'failed-precondition',
>    name: 'FirebaseError',
>    toString: [Function] }
>  { Error [FirebaseError]: The query requires an index. You can create it here: https://console.firebase.google.com/project/mohamed-amine-jallouli/database/firestore/indexes?create_composite=ClVwcm9qZWN0cy9tb2hhbWVkLWFtaW5lLWphbGxvdWxpL2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9oZXJvZXMvaW5kZXhlcy9fEAEaCwoHZGVmYXVsdBACGgkKBWxpa2VzEAIaDAoIX19uYW1lX18QAg
>      at new FirestoreError (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js:353:28)
>      at JsonProtoSerializer.fromRpcStatus (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js:5579:16)
>      at JsonProtoSerializer.fromWatchChange (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js:6076:44)
>      at PersistentListenStream.onMessage (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js:14286:43)
>      at /home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js:14215:30
>      at /home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js:14255:28
>      at /home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/@firebase/firestore/dist/index.node.cjs.js:7343:20
>      at ZoneDelegate.invoke (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:391:26)
>      at Zone.run (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:150:43)
>      at /home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:889:34
>      at ZoneDelegate.invokeTask (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:423:31)
>      at Zone.runTask (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:195:47)
>      at drainMicroTaskQueue (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:601:35)
>      at ZoneTask.invokeTask (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:502:21)
>      at ClientDuplexStream.ZoneTask.invoke (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/zone.js/dist/zone-node.js:487:48)
>      at ClientDuplexStream.emit (events.js:193:13)
>      at ClientDuplexStream.EventEmitter.emit (domain.js:481:20)
>      at addChunk (_stream_readable.js:295:12)
>      at readableAddChunk (_stream_readable.js:276:11)
>      at ClientDuplexStream.Readable.push (_stream_readable.js:231:10)
>      at Object.onReceiveMessage (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/grpc/src/client_interceptors.js:1292:19)
>      at InterceptingListener.recvMessageWithContext (/home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/grpc/src/client_interceptors.js:607:19)
>      at /home/amine/Documents/docker-projects/angular7-example-app/functions/node_modules/grpc/src/client_interceptors.js:706:14
>    code: 'failed-precondition',
>    name: 'FirebaseError',
>    toString: [Function] }
>  getHeroes failed: The query requires an index. You can create it here: https://console.firebase.google.com/project/mohamed-amine-jallouli/database/firestore/indexes?create_composite=ClVwcm9qZWN0cy9tb2hhbWVkLWFtaW5lLWphbGxvdWxpL2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9oZXJvZXMvaW5kZXhlcy9fEAEaCwoHZGVmYXVsdBACGgkKBWxpa2VzEAIaDAoIX19uYW1lX18QAg
>  getHeroes failed: The query requires an index. You can create it here: https://console.firebase.google.com/project/mohamed-amine-jallouli/database/firestore/indexes?create_composite=ClVwcm9qZWN0cy9tb2hhbWVkLWFtaW5lLWphbGxvdWxpL2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9oZXJvZXMvaW5kZXhlcy9fEAEaCwoHZGVmYXVsdBACGgkKBWxpa2VzEAIaDAoIX19uYW1lX18QAg
127.0.0.1 - - [05/Jun/2019:04:51:42 +0000] "GET / HTTP/1.1" 504 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
^CShutting down...
```

**Comment by Ismaestro** [comment]
mm why are you using firebase serve? can you use npm run serve:ssr instead?

**Comment by Ismaestro** [comment]
Also,
```
Billing account not configured. External network is not accessible and quotas are severely limited. Configure billing account to remove these restrictions
Node Express server listening on port 8080
```
this happends because with the basic firebase plan you cannot point the app to an external network. See [this](https://stackoverflow.com/a/51154352/1919749).
